### ISSUE TITLE
Static Sounds/Images. Don't delete this card it contains an important file

### ISSUE THREAD

**Issue by Gardengul** [Vilhelm-Ian/Interactive_And_Randomize_Anki_Note_Types#4]
[Static Sounds/Images](https://docs.ankiweb.net/templates/fields.html#static-soundsimages)

If there is a need to have a sound that is used only in the template but is not attached to any field of the note, then you need to set the correct name.

1-second-and-500-milliseconds-of-silence.mp3
_1-second-and-500-milliseconds-of-silence.mp3

**Comment by Vilhelm-Ian** [comment]
thanks I added the change
